### ISSUE TITLE
Configure Vagrant and Add Dependencies

### ISSUE THREAD

**Issue by itsAnth** [customers-devops-2019/customers#11]
**As a** developer
**I need** dependencies in Vagrant
**So that** don't have to install them manually

**Assumptions:**
We will need the following packages:
Flask==1.0.2
Flask-API==1.1
Flask-SQLAlchemy==2.3.2
nose==1.3.7
pinocchio==0.4.2
coverage==4.5.2

**Acceptance Criteria:**
Should be able to start the Python REPL from the CLI and check Flask version

**Comment by ethankessinger** [comment]
@itsAnth I actually don't know how to QA this. Can you make sure one more time it's hitting the criteria and then move to done?
