### ISSUE TITLE
Duplicative: Write test cases to test model

### ISSUE THREAD

**Issue by tedwatson** [customers-devops-2019/customers#21]
**As a** ...
**I need** ...
**So that** ...

**Assumptions:**
*...

**Acceptance Criteria:**
...
Given ...
When ...
Then ...

**Comment by tedwatson** [comment]
I put this in the icebox and left the acceptance criteria blank because I'm not sure what exactly we should be testing yet

**Comment by itsAnth** [comment]
I think we can delete this one because we have tested the model file methods separately
