### ISSUE TITLE
Create test for "Read" function

### ISSUE THREAD

**Issue by tedwatson** [customers-devops-2019/customers#24]
As a developer
I need to define tests
So that I know that my "read" command is working as intended

Assumptions:
Run these tests using nosetest as I develop

Acceptance Criteria:
When I run the test, it passes. If I change the code to make it fail, it fails.

**Comment by tedwatson** [comment]
I see this has gone into "Review/QA" but I can't find the code for it in test_customers.py nor can I find it anywhere else, can someone point me in the right direction?

**Comment by itsAnth** [comment]
@tedwatson Good catch. I believe the service is created already but not the test. I may have accidentally dragged this one into QA too soon.
