### ISSUE TITLE
Create working "update" function and tests

### ISSUE THREAD

**Issue by tedwatson** [customers-devops-2019/customers#25]
**As a developer**
I need to add to the update function so that it correctly interacts with our db and write tests updating the name attribute
So that I know that my "update" command is working as intended for updating names

**Assumptions:**
Interact with the SQLite test db
Run these tests using nosetest as I develop

**Acceptance Criteria:**
I should be able to use a put command to update a record
When I run the test, it passes. If I change the code to make it fail, it fails.

**Comment by ethankessinger** [comment]
Adding another ticket to write tests for checking if email update works since I did not do this for this card. Changed the story points here down to 5 and will do a small for the additional tests
