### ISSUE TITLE
Add Action Service Test

### ISSUE THREAD

**Issue by itsAnth** [customers-devops-2019/customers#39]
**As a** developer
**I need** to test the unsubscribe service
**So that** we know it works as intended

**Assumptions:**
/customers/id/unsubscribe is the path

**Acceptance Criteria:**
PUT request /customers/id/unsubscribe should set subscribe field to false and the response should be a customer object

**Comment by ethankessinger** [comment]
@itsAnth did you already do this? If so lets move to done

**Comment by itsAnth** [comment]
Yes, I can move it over
