### ISSUE TITLE
Increase test coverage of find attributes

### ISSUE THREAD

**Issue by ii397** [customers-devops-2019/customers#42]
**As a** Developer 
**I need** To increase test coverage for all Find address attributes  
**So that** Coverage of test on all code is more than 95%

**Assumptions:**
* Run coverage tool: $ pip install coverage
* We will track tests for errors in another card

**Acceptance Criteria:**
...
Given All test cases are written 
When I run the coverage tool 
Then I get over 95% coverage for all code

**Comment by ethankessinger** [comment]
Updated the test_customers.py with following tests:
- Find Customers by address1
- Find Customers by address2
- Find Customers by city
- Find Customers by country
- Find Customers by state(province)
- Find Customers by subscribed
- Find Customers by zip

This gets coverage of test_customers.py up to 93%
