### ISSUE TITLE
Run PyLint and make syntax fixes if needed

### ISSUE THREAD

**Issue by ii397** [customers-devops-2019/customers#44]
**As a** a developer
**I need** to increase PyLint score to 9/10 or above
**So that** our code conforms to PEP8 Python standards

**Assumptions:**
* Already have PyLint installed 
* In terminal, running pylint tests gets score and lines needing changes

**Acceptance Criteria:**
When I run PyLint 
Then I get a 9/10 score or above

**Comment by ethankessinger** [comment]
Initial score 8.4

Lines shouldn't be more than 100 characters. Here's the correct way to have that code moved to multiple lines:
customer = Customer(firstname="John", lastname="Doe", email="fake1@email.com", 
                                      subscribed=False, address1="123 Main St", address2="1B", 
                                      city="New York", country="USA", province="NY", zip="12310"
                                      )

Methods cannot be more than 32 characters

Variables should be in snake case (snake_case) not in camel case (camelCase)

After changes, score 9.71 and verified all tests still pass
