### ISSUE TITLE
Bind database service to Cloud Foundry app

### ISSUE THREAD

**Issue by ethankessinger** [customers-devops-2019/customers#51]
**As a** developer
**I need** bind the database service to the Cloud Foundry app
**So that** we can ensure the code runs in any cloud environment

**Assumptions:**
* We have already created and properly set up our database

**Acceptance Criteria:**
Our Cloud Foundry app will be able to run on multiple environments

**Comment by ii397** [comment]
Create the org first then in services, database, cloudfoundry create a connection to the common app
