### ISSUE TITLE
Create the Read Flask Service

### ISSUE THREAD

**Issue by itsAnth** [customers-devops-2019/customers#6]
**As a** developer
**I need** a **read** service for customers
**So that** I can retrieve data from the database

**Assumptions:**
It will use the HTTP GET method
It will follow the RESTful design
We are only building the service structure. It will **not** interface with the database
We will use flask
It will follow the service structure in the README.md file
Its should **not** work with any other method other than GET

**Acceptance Criteria:**
When I perform a GET method on the route, it will return a JSON object with the status 200
`{
  data: 'You executed the read route'
}`

**Comment by ethankessinger** [comment]
Break into 4
