### ISSUE TITLE
Persistence to the Vagrantfile as a Docker container

### ISSUE THREAD

**Issue by ii397** [customers-devops-2019/customers#63]
**As a** Developer 
**I need** Add persistence to the Vagrantfile as a Docker container.
**So that**  we can package up the application with all of the parts needed to run persistence and continuous integration

**Assumptions:**
* The method of persistence used in the application is the one that will run in the Docker container

**Acceptance Criteria:**
Given the need to package up all files within an application 
When deploying a microservice application
Then the docker container will consolidate the package in its entirety

**Comment by itsAnth** [comment]
This is the same at issue 60
