### ISSUE TITLE
README Update

### ISSUE THREAD

**Issue by itsAnth** [customers-devops-2019/customers#74]
**As a** member of the external development and operations teams
**I need** comprehensive and up to date information
**So that** I can leverage the customer's microservice in the e-commerce application.

**Assumptions:**
We will update the README.md file to have the latest information

**Acceptance Criteria:**
When I view the README in the repository
Then I should have a clear understanding of how to use the service and where to access the endpoint

**Comment by ethankessinger** [comment]
Link to our service: https://nyu-customer-service-s19.mybluemix.net/
