### ISSUE TITLE
Add BDD automated test for DELETE in application UI

### ISSUE THREAD

**Issue by ii397** [customers-devops-2019/customers#83]
**As a** user
**I need** to ensure that a customer can be deleted  in the UI
**So that** the application can behave properly when the user is interacting with customer database

**Assumptions:**
* feature is written using Gherkin syntax
* feature and steps file already exists
* Run the behave command and examine the results

**Acceptance Criteria:**
    When I visit the "Home Page"
    And I press the "Search" button
    Then I should see "John" in the results
    When I set the "ID" to "John"
    And I copy the "ID" field
    And I paste the "ID" field
    When I press the "Delete" button
    Then I should see the message "Success"
    When I press the "Clear" button
    And I set the "City" to "Toronto"
    And I press the "Search" button
    Then I should see "Steve" in the results
    And I should not see "John" in the results

**Comment by ethankessinger** [comment]
Scenario: Delete a Customer
    When I visit the "Home Page"
    And I press the "Clear" button
    And I set the "City" to "Toronto"
    And I press the "Search" button
    Then I should see the message "Success"
    And I should see "John" in the results
    When I copy the "Id" field
    And I press the "Clear" button
    And I paste the "Id" field
    When I press the "Delete" button
    And I press the "Clear" button
    And I set the "City" to "Toronto"
    And I press the "Search" button
    Then I should see "Steve" in the results
    and I should not see "John" in the results

This keeps failing but It works when I manually test it, so stumped on this. @itsAnth any ideas?
<img width="975" alt="Screen Shot 2019-04-29 at 3 00 58 PM" src="https://user-images.githubusercontent.com/6600166/56919860-b0c3cb80-6a8f-11e9-8e5f-3136df5d61e5.png">
